#Overall Filter Parameters

min_particles: 500
max_particles: 2000
kld_err: 0.05
kld_z: 0.99
update_min_d: 0.1
update_min_a: 0.1
update_min_t: 0    # 0 = not used

resample_interval: 1.0
transform_tolerance: 0.5
recovery_alpha_slow: 0.0001
recovery_alpha_fast: 0.001

initial_pose_x: 2.0
initial_pose_y: 1.0
initial_pose_a: -1.6
initial_cov_xx: 0.0
initial_cov_yy: 0.0
initial_cov_aa: 0.0

gui_publish_rate: 1.0
save_pose_rate: 0.5
use_map_topic: true
first_map_only: true

#Laser Model Parameters

laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 30
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

#Odometry Model Parameters

odom_model_type: omni
odom_alpha1: 0.8
odom_alpha2: 0.8
odom_alpha3: 0.8
odom_alpha4: 0.8
odom_alpha5: 0.8

odom_frame_id: "/odom"
base_frame_id: "/base_footprint"
global_frame_id: "/map"



