## -----------------------------------------
# All parameters at: wiki.ros.org/costmap_2d
## -----------------------------------------

## ---------------------------
# Costmap dependent parameters
#  - global costmap
#  - local costmap
## ---------------------------

footprint: [[0.285, -0.19], [-0.285, -0.19], [-0.36, -0.05], [-0.36, 0.05], [-0.285, 0.19], [0.285, 0.19], [0.37, 0.08], [0.37, -0.08]]

# --- costmap:
transform_tolerance:   0.2
publish_frequency:     2.0

resolution: 0.01

# --- obstacle layer:
#track_unknown_space:   false
publish_voxel_map:     false

obstacle_range:        1.5
raytrace_range:        1.5
max_obstacle_height:   1.2

obstacle_layer:
    observation_sources:   laser_scan_front laser_scan_back

    laser_scan_front:
        topic:                    /scan_filtered
        sensor_frame:             base_laser_front_link
        data_type:                LaserScan
        observation_persistence:  0.0
        expected_update_rate:     0.4
        marking:                  true
        clearing:                 true
        min_obstacle_height:      -0.1
        max_obstacle_height:      1.2
        min_obstalce_range:       0.5
        obstacle_range:           1.5
        raytrace_range:           1.5
        inf_is_valid:             true

    laser_scan_back:
        topic:                    /scan_back_filtered
        sensor_frame:             base_laser_back_link
        data_type:                LaserScan
        observation_persistence:  0.0
        expected_update_rate:     0.4
        marking:                  true
        clearing:                 true
        min_obstacle_height:      -0.1
        max_obstacle_height:      1.2
        min_obstalce_range:       0.5
        obstacle_range:           1.5
        raytrace_range:           1.5
        inf_is_valid:             true

#barrier_tape_layer:
#    observation_sources: barrier_scan

#    barrier_scan:
#      topic:                    /barrier_detector/points
#      sensor_frame:             /base_footprint
#      data_type:                PointCloud2
#      observation_persistence:  0.0
#      marking:                  true
#      obstacle_range:           1.5
#      raytrace_range:           1.5
#      clearing:                 true

