#-------------SPEED----------------------------

max_trans_vel: 0.55              #default : 0.55, fast params: 1.0
min_trans_vel: 0.1              #default : 0.1

max_vel_y: 0.1                  #default : 0.1
min_vel_y: -0.1                 #default : -0.1

max_vel_x: 0.55                  #_default : 0.55
min_vel_x: -0.05                #_default : 0.0



max_rot_vel: 1.5                #default : 1.0, fast params: 1.5
min_rot_vel: 0.15                #default : 0.4

acc_lim_x: 1.5                  #default : 2.5
acc_lim_y: 1.5                  #default : 2.5
acc_lim_theta: 3.2              #default : 3.2, fast params: 3.2
acc_limit_trans: 0.5            #default : 0.1, fast params: 1.5

#----------------------------------------------

goal_distance_bias: 19.0        #default : 24.0, fast params: 14.0
path_distance_bias: 33.0        #default : 32.0, fast params: 35.0


occdist_scale: 0.03             #default : 0.01

sim_time: 1.7                   #default : 1.7
sim_granularity: 0.025          #default : 0.025
angular_sim_granularity: 0.1


stop_time_buffer: 0.4           #default : 0.2
oscillation_reset_dist: 0.05    #default : 0.05

forward_point_distance: 0.325    #default : 0.325, fast params: 0.25

scaling_speed: 0.25             #default : 0.25, fast params: 0.35
max_scaling_factor: 0.2         #default : 0.2, fast params: 0.1


vx_samples: 5                   #default : 3
vy_samples: 6                   #default : 10
vtheta_samples: 20              #default : 20

sim_period: 0.2                 #default : not found

xy_goal_tolerance: 0.05        #default : 0.10, fast params: 0.075
yaw_goal_tolerance: 0.57         #default : 0.05
latch_xy_goal_tolerance: true   #default : false, fast params: true

rot_stopped_vel: 0.02           #default : not found
trans_stopped_vel: 0.02         #default : not found

penalize_negative_x: true      #default : true
use_dwa: true
restore_defaults: false
prune_plan: false #default true
#publish_cost_grid_pc: true
publish_traj_pc: false
cheat_factor: 3.0

